BookingAppTeam7/Back-end

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReservationController.java, BookingApp/src/main/java/com/booking/BookingApp/models/Reservation.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/reservations/ReservationPostDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/reservations/ReservationPutDTO.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IReservationRepository.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/ReservationRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/IReservationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReservationService.java
Added reservation controller , models and DTO
=> Added reservation controller

BookingApp/src/main/java/com/booking/BookingApp/contollers/UserController.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/UserRepository.java
Changed return values of users controller function. Added different http status codes as return values.
=> Changed return values of controllers functions

BookingApp/src/main/java/com/booking/BookingApp/repositories/UserRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserService.java
=> Fixed bug in User Service update function

BookingApp/src/main/java/com/booking/BookingApp/contollers/PriceCardController.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/accommodations/PriceCardPostDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/accommodations/PriceCardPutDTO.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IPriceCardRepository.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/PriceCardRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/IPriceCardService.java, BookingApp/src/main/java/com/booking/BookingApp/services/PriceCardService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserService.java
Created PriceCardController , PriceCardService, PriceCardRepository ,PriceCard - Post,Put DTOs objects and enabled CRUD operations.
=> Created PriceCardController with CRUD end-points

BookingApp/src/main/java/com/booking/BookingApp/contollers/AccommodationController.java, BookingApp/src/main/java/com/booking/BookingApp/contollers/PriceCardController.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/Accommodation.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/Location.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/PriceCard.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/Review.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/TimeSlot.java, BookingApp/src/main/java/com/booking/BookingApp/services/IPriceCardService.java, BookingApp/src/main/java/com/booking/BookingApp/services/PriceCardService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReviewService.java, BookingApp/src/main/java/com/booking/BookingApp/services/TimeSlotService.java
Enabled updating of accommodations data.
=> Feature/updating accommodations data 2.2

BookingApp/src/main/java/com/booking/BookingApp/contollers/AccommodationController.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/Accommodation.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IAccommodationRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/AccommodationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IAccommodationService.java
Added end point for getting accommodations by status and updating accommodations status.
=> Added new end points in Accommodation controller

BookingApp/src/main/java/com/booking/BookingApp/services/IUserValidatorService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserValidatorService.java
Added validation for user registration and edit
=> Added validations

BookingApp/src/main/java/com/booking/BookingApp/contollers/AccommodationController.java, BookingApp/src/main/java/com/booking/BookingApp/contollers/PriceCardController.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/PriceCard.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/accommodations/PriceCardPutDTO.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IAccommodationRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/AccommodationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/AccommodationValidatorService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IAccommodationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IAccommodationValidatorService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IPriceCardService.java, BookingApp/src/main/java/com/booking/BookingApp/services/PriceCardService.java
Updated validation functions. Return value is BAD_REQUEST, not IllegalException.
=> Feature/admin accommodations requests 4.2

BookingApp/src/main/java/com/booking/BookingApp/contollers/AccommodationRequestController.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/Accommodation.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/AccommodationRequest.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/accommodations/AccommodationRequestPostDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/accommodations/AccommodationRequestPutDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/enums/AccommodationRequestStatus.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IAccommodationRequestRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/AccommodationRequestService.java, BookingApp/src/main/java/com/booking/BookingApp/services/AccommodationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IAccommodationRequestService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IAccommodationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/PriceCardService.java
When owner create or edit an accommodation object, change is not instant visible in database - AccommodationRequest is created. When admin approve or reject change, accommodations data will be updated and APPROVED/BLOCKED and this request will be APPROVED/REJECTED.
=> Admin accommodation requests fixed

BookingApp/src/main/java/com/booking/BookingApp/contollers/UserController.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserService.java
Added funvtion FindUserById which returns whole User object
=> Added new findById (mobile app helper)

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReservationController.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IReservationRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/AccommodationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IReservationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReservationService.java
Added function which change status of reservation request into APPROVED/REJECTED. Enabled review of all accommodation`s request.
=> Added function for confirming/rejecting reservation request

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReservationController.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/reservations/ReservationGetDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/reservations/Reservation.java, BookingApp/src/main/java/com/booking/BookingApp/services/IReservationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReservationService.java
Enabled review of all guests reservations. Enabled cancelling approved reservation if it doesn`t meet cancellation deadline.
=> Guests reservations management 3.2

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReviewController.java, BookingApp/src/main/java/com/booking/BookingApp/models/accommodations/Review.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/review/ReviewPostDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/review/ReviewPutDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/enums/ReviewStatusEnum.java, BookingApp/src/main/java/com/booking/BookingApp/services/IReviewService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReviewService.java
Addded owner rating functionalities in backand and fixed Review controller
=> Added owner rating feature

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReviewController.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/review/ReviewPostDTO.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReviewService.java
Added check if it's possible to create review
=> Fixed accommodation rating

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReviewController.java, BookingApp/src/main/java/com/booking/BookingApp/contollers/UserController.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IReviewRepository.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IUserRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/IReviewService.java, BookingApp/src/main/java/com/booking/BookingApp/services/IUserService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReviewService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserService.java
Added end-points for getting user by it`s role and getting reviews for exact owner/accommodation.
=> Added necessarry end-points in user and review controllers

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReviewController.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IReviewRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/IReviewService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReviewService.java
Admin can approve or reject reported accommodation/owner review.
=> Added necessarry end-points for updating review request status

BookingApp/src/main/java/com/booking/BookingApp/contollers/UserController.java, BookingApp/src/main/java/com/booking/BookingApp/contollers/UserReportController.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/reports/UserReportPostDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/dtos/users/UserPutDTO.java, BookingApp/src/main/java/com/booking/BookingApp/models/reports/UserReport.java, BookingApp/src/main/java/com/booking/BookingApp/models/users/Guest.java, BookingApp/src/main/java/com/booking/BookingApp/models/users/User.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IUserReportRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/IUserReportService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserReportService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserService.java
The owner can report a guest and provide a reason for the report only if the guest has had at least one reservation in the past at one of their accommodations. Similarly, the guest can report the owner if they have been a guest at their accommodation.
=> Added user reports

BookingApp/src/main/java/com/booking/BookingApp/contollers/UserReportController.java, BookingApp/src/main/java/com/booking/BookingApp/models/reports/UserReport.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IUserReportRepository.java, BookingApp/src/main/java/com/booking/BookingApp/repositories/IUserRepository.java, BookingApp/src/main/java/com/booking/BookingApp/services/IUserReportService.java, BookingApp/src/main/java/com/booking/BookingApp/services/UserReportService.java
Added feature for admin to view all report requests for exact user and to deactivate user or to close report.
=> Feature/report requests 4.5

BookingApp/pom.xml, BookingApp/src/test/java/com/booking/BookingApp/controllers/ReservationControllerIntegrationTest.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/pages/GuestHomePage.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/pages/GuestReservationsPage.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/pages/HomePage.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/pages/LogInPage.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/tests/TestBase.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/tests/student2/Student2Test.java
Added necessarry dependencies and corrected ReservationIntegrationControllerClass .
=> Added pages for selenium tests

BookingApp/src/main/java/com/booking/BookingApp/services/ReservationService.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/pages/GuestReservationsPage.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/tests/student2/ReservationTable.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/tests/student2/Student2Test.java
Added e2e test for reservation cancellation by guest. Tested case when exists reservation with pending status in same time slot as cancelled reservation - pending reservation will be approved. Also tested case when it`s not possible to cancel reservation because of accommodations deadline.
=> Test selenium/reservation cancellation 1

BookingApp/src/test/java/com/booking/BookingApp/e2e/tests/student2/Student2Test.java
=> Selenium test/reservation confirmation 2

BookingApp/src/main/java/com/booking/BookingApp/contollers/ReservationController.java, BookingApp/src/test/java/com/booking/BookingApp/controllers/ReservationControllerCreateIntegrationTest.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/pages/SearchedAccommodationsPage.java, BookingApp/src/test/java/com/booking/BookingApp/e2e/tests/student3/Student3Test.java, BookingApp/src/test/resources/application-test.properties, BookingApp/src/test/resources/test-data-luka.sql
Parametrized selenium tests, authorized controller tests
=> Fixed back-end tests

BookingApp/src/main/java/com/booking/BookingApp/services/ReservationService.java, BookingApp/src/main/java/com/booking/BookingApp/services/ReviewService.java, BookingApp/src/test/java/com/booking/BookingApp/controllers/ReservationControllerIntegrationTest.java, BookingApp/src/test/java/com/booking/BookingApp/services/ReservationServiceTest.java, BookingApp/src/test/resources/application-test.properties, BookingApp/src/test/resources/test-data.sql
=> Added check if there are existing approved reservations in same accommodation
